'use client';

import React, { useState, useEffect } from 'react';
import { NewariCalendar, NewariDate } from '@/types/newari-calendar';

interface NewariCalendarProps {
  onDateSelect?: (date: NewariDate) => void;
}

export default function NewariCalendarComponent({ onDateSelect }: NewariCalendarProps) {
  const [calendar, setCalendar] = useState<NewariCalendar | null>(null);
  const [loading, setLoading] = useState(true);
  const [currentDate, setCurrentDate] = useState(new Date());

  useEffect(() => {
    loadNewariCalendar();
  }, [currentDate]);

  const loadNewariCalendar = async () => {
    try {
      setLoading(true);
      const year = currentDate.getFullYear();
      const month = currentDate.getMonth() + 1;
      
      const response = await fetch(`/api/newari-calendars?year=${year}&month=${month}`);
      const result = await response.json();
      
      if (result.success && result.data.length > 0) {
        setCalendar(result.data[0]);
      } else {
        // Generate fallback calendar
        setCalendar(generateFallbackCalendar(year, month));
      }
    } catch (error) {
      console.error('Error loading Newari calendar:', error);
      setCalendar(generateFallbackCalendar(
        currentDate.getFullYear(), 
        currentDate.getMonth() + 1
      ));
    } finally {
      setLoading(false);
    }
  };

  const generateFallbackCalendar = (year: number, month: number): NewariCalendar => {
    const newariYear = year - 879;
    const newariMonths = ['कछला', 'थिंला', 'पोहेला', 'सिला', 'चिला', 'चौला', 
                         'बछला', 'तछला', 'दिल्ला', 'गुंला', 'ञला', 'कौला'];
    
    return {
      id: parseInt(`${year}${month}`),
      englishYear: year,
      newariYear,
      month,
      monthName: ['Baisakh', 'Jestha', 'Ashadh', 'Shrawan', 'Bhadra', 'Ashwin',
                 'Kartik', 'Mangsir', 'Poush', 'Magh', 'Falgun', 'Chaitra'][month - 1],
      monthNameNewari: newariMonths[month - 1],
      calendarData: [], // Will be generated by frontend
      festivals: ['योमरी पुन्हि', 'स्वन्ति: नखः', 'घ्यात्रु ख्वाः स्विगु'],
      importantDays: ['गुणला', 'मोहनी', 'स्वन्ति'],
      scrapedUrl: '',
      scrapedAt: new Date()
    };
  };

  const handleDateClick = (date: NewariDate) => {
    onDateSelect?.(date);
  };

  const navigateMonth = (direction: 'prev' | 'next') => {
    const newDate = new Date(currentDate);
    newDate.setMonth(newDate.getMonth() + (direction === 'next' ? 1 : -1));
    setCurrentDate(newDate);
  };

  if (loading) {
    return (
      <div className="flex justify-center items-center h-96">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-yellow-600 mx-auto"></div>
          <p className="mt-4 text-gray-600">नेपाल भाषा पात्रो ल्याइदै...</p>
        </div>
      </div>
    );
  }

  if (!calendar) {
    return (
      <div className="text-center text-red-600 p-8">
        पात्रो ल्याउन सकिएन। कृपया पुनः प्रयास गर्नुहोस्।
      </div>
    );
  }

  return (
    <div className="bg-yellow-50 rounded-lg shadow-lg p-6 max-w-6xl mx-auto">
      {/* Header */}
      <div className="text-center mb-8">
        <h1 className="text-3xl font-bold text-yellow-800 mb-2">
          नेपाल भाषा पात्रो
        </h1>
        <h2 className="text-2xl text-yellow-700">
          {calendar.monthNameNewari} {calendar.newariYear} नेपाल संवत्
        </h2>
        <p className="text-lg text-yellow-600">
          {calendar.monthName} {calendar.englishYear}
        </p>
      </div>

      {/* Calendar Grid */}
      <div className="bg-white rounded-lg p-4 mb-6">
        <div className="grid grid-cols-7 gap-2 mb-4">
          {['आइत', 'सोम', 'मंगल', 'बुध', 'बिहि', 'शुक्र', 'शनी'].map(day => (
            <div key={day} className="text-center font-bold text-yellow-700 py-2 border-b">
              {day}
            </div>
          ))}
        </div>

        {/* Calendar days would go here */}
        <div className="text-center py-8 text-gray-500">
          नेपाल भाषा पात्रोको दिनहरू यहाँ देखाइनेछ
        </div>
      </div>

      {/* Festivals Section */}
      <div className="grid md:grid-cols-2 gap-6">
        <div className="bg-yellow-100 rounded-lg p-4">
          <h3 className="font-bold text-yellow-800 mb-3 text-lg">नेवारी चाडपर्वहरू</h3>
          <ul className="space-y-2">
            {calendar.festivals.map((festival, index) => (
              <li key={index} className="flex items-center text-yellow-700">
                <span className="w-2 h-2 bg-yellow-500 rounded-full mr-3"></span>
                {festival}
              </li>
            ))}
          </ul>
        </div>

        <div className="bg-red-100 rounded-lg p-4">
          <h3 className="font-bold text-red-800 mb-3 text-lg">महत्वपूर्ण दिनहरू</h3>
          <ul className="space-y-2">
            {calendar.importantDays.map((day, index) => (
              <li key={index} className="flex items-center text-red-700">
                <span className="w-2 h-2 bg-red-500 rounded-full mr-3"></span>
                {day}
              </li>
            ))}
          </ul>
        </div>
      </div>
    </div>
  );
}